### ISSUE TITLE
IRF interpolation at grid boundries

### ISSUE THREAD

**Issue by steob92** [VERITAS-Observatory/V2DL3#61]
scipy.interpolate.RegularGridInterpolator by default throws an error when the interpolated coordinates are outside of the grid boundries.  

I believe in Event Display when this happens we extrapolate to the coordinates? This can be enabled by giving the options bounds_error=False, fill_value=None. 

From:
https://github.com/VERITAS-Observatory/V2DL3/blob/a78086ef2fcd857e8b6aafc6c64c815ab4bbe440/pyV2DL3/eventdisplay/IrfInterpolator.py#L40

To:
https://github.com/VERITAS-Observatory/V2DL3/blob/aac0ae5e955fd8ac1067cda0f06324ac51fe9ae3/pyV2DL3/eventdisplay/IrfInterpolator.py#L40

This should be fine for nearby extrapolations (say $\Delta$Ze ~5) but we'd want to be careful for extreme extrapolations. 

Example error:
```
(v2dl3) cperron@romulus:/raid/jacko/cperron/user_data/FITS/LS5039/fit$ ./v2dl3_for_runlist_from_ED485-anasum.sh 
DEBUG:root:Start importing ROOT
/raid/jacko/cperron/conda/envs/v2dl3/lib/python3.7/site-packages/root_numpy/__init__.py:34: RuntimeWarning: ROOT 6.22/02 is currently active but you installed root_numpy against ROOT 6.22/06. Please consider reinstalling root_numpy for this ROOT version.
  RuntimeWarning)
Datasource: EventDisplay
TClass::Init:0: RuntimeWarning: no dictionary for class VTMVAEvaluatorResults is available
TClass::Init:0: RuntimeWarning: no dictionary for class VTMVAEvaluatorData is available
TClass::Init:0: RuntimeWarning: no dictionary for class VGammaHadronCuts is available
TClass::Init:0: RuntimeWarning: no dictionary for class VAnalysisUtilities is available
TClass::Init:0: RuntimeWarning: no dictionary for class VInstrumentResponseFunctionRunParameter is available
Coordinates to fillresponse: 215.3098794023627 53.6583840668722 7.598926282051282 0
Full-enclosure:  camera offsets:  [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ] noise: 7.598926282051282 zenith: 53.6583840668722
Azimuth 215.3098794023627
Single index True
Coordinate tuple False
Extracting IRFs of type: effNoTh2
az bin to store:  1
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 235620/235620 [00:03<00:00, 61499.89it/s]
Interpolating coordinates:  [7.598926282051282, 53.6583840668722, 0.0]
Traceback (most recent call last):
  File "/raid/jacko/cperron/conda/envs/v2dl3/bin/v2dl3", line 8, in <module>
    sys.exit(cli())
  File "/raid/jacko/cperron/conda/envs/v2dl3/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/raid/jacko/cperron/conda/envs/v2dl3/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/raid/jacko/cperron/conda/envs/v2dl3/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/raid/jacko/cperron/conda/envs/v2dl3/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/raid/jacko/cperron/conda/envs/v2dl3/lib/python3.7/site-packages/pyV2DL3/script/v2dl3.py", line 85, in cli
    datasource.fill_data()
  File "/raid/jacko/cperron/conda/envs/v2dl3/lib/python3.7/site-packages/pyV2DL3/VtsDataSource.py", line 18, in fill_data
    self.__fill_response__(**kwargs)
  File "/raid/jacko/cperron/conda/envs/v2dl3/lib/python3.7/site-packages/pyV2DL3/eventdisplay/EventDisplayDataSource.py", line 38, in __fill_response__
    self.__irf_to_store__)
  File "/raid/jacko/cperron/conda/envs/v2dl3/lib/python3.7/site-packages/pyV2DL3/eventdisplay/fillRESPONSE.py", line 122, in __fillRESPONSE__
    eff_area, axis = irf_interpolator.interpolate([noise, zenith, offset])
  File "/raid/jacko/cperron/conda/envs/v2dl3/lib/python3.7/site-packages/pyV2DL3/eventdisplay/IrfInterpolator.py", line 53, in interpolate
    coordinate[2]))
  File "/raid/jacko/cperron/conda/envs/v2dl3/lib/python3.7/site-packages/scipy/interpolate/interpolate.py", line 2510, in __call__
    "in dimension %d" % i)
ValueError: One of the requested xi is out of bounds in dimension 2
```

**Comment by GernotMaier** [comment]
@sona-patel - this is now as well implemented? Did you document the new command line parameters? If yes, where?

**Comment by sona-patel** [comment]
Yes, it is implemented now! 

The information of these two new command line parameters appear with `--help` option. The detail documentation will be followed by #113, early next week.

**Comment by GernotMaier** [comment]
Good, so let's close this issue.
